/* =========================================================
 * knowledge.js — built-in offline reasoning corpus.
 * Powers the "web-search-style" analyzer: archetype lexicon,
 * real-world reference dimensions & part-ratio facts.
 * No network calls are made; this is the local knowledge base
 * that the File-Attachment + Search reasoning tools query.
 * ======================================================= */
(function () {
  'use strict';

  /* -------- archetypes: parametric part recipes -------- */
  // Each part: kind (primitive family), params, offset [x,y,z], scale,
  // parent (for joint chain), color role, mirrored (left/right pair).
  const ARCHETYPES = {
    quadruped: {
      label: 'Quadruped creature',
      glyph: '🐺',
      keywords: ['dog','cat','wolf','lion','tiger','horse','fox','bear','animal','quadruped','pet','puppy','kitten','leopard','cheetah','cow','deer'],
      joints: [['root',0,0.75,0],['spine','root',0,0.95,0],['neck','spine',0,1.05,0.62],['head','neck',0,1.12,0.98],
               ['tail','spine',0,0.92,-0.72],
               ['legFL','spine',0.34,0.72,0.5],['legFR','spine',-0.34,0.72,0.5],
               ['legBL','spine',0.34,0.72,-0.5],['legBR','spine',-0.34,0.72,-0.5]],
      parts: [
        { id:'body',   kind:'capsule', p:{r:0.42,len:1.1}, pos:[0,0.85,0], rot:[Math.PI/2,0,0], role:'primary' },
        { id:'chest',  kind:'sphere',  p:{r:0.46}, pos:[0,0.88,0.45], role:'primary' },
        { id:'hip',    kind:'sphere',  p:{r:0.4},  pos:[0,0.85,-0.5], role:'primary' },
        { id:'head',   kind:'sphere',  p:{r:0.3},  pos:[0,1.15,1.0],  role:'primary', parent:'head' },
        { id:'snout',  kind:'box',     p:{w:0.2,h:0.16,d:0.3}, pos:[0,1.08,1.3], role:'secondary', parent:'head' },
        { id:'earL',   kind:'cone',    p:{r:0.1,h:0.2}, pos:[0.16,1.4,0.95], role:'accent', mirror:true, parent:'head' },
        { id:'tail',   kind:'cylinder',p:{r:0.07,h:0.7}, pos:[0,0.95,-0.95], rot:[-Math.PI/3,0,0], role:'secondary', parent:'tail' },
        { id:'leg',    kind:'cylinder',p:{r:0.1,h:0.62}, pos:[0.3,0.42,0.5], role:'limb', mirror:true, pairZ:0.5, count:4, parent:'legFL' },
        { id:'paw',    kind:'sphere',  p:{r:0.12}, pos:[0.3,0.1,0.5], role:'accent', mirror:true, pairZ:0.5, count:4, parent:'legFL' },
      ],
    },
    bipedal: {
      label: 'Bipedal humanoid / mech',
      glyph: '🤖',
      keywords: ['human','person','robot','mech','android','biped','soldier','character','man','woman','golem','cyborg','warrior','astronaut'],
      joints: [['root',0,1.0,0],['spine','root',0,1.25,0],['chest','spine',0,1.55,0],['head','chest',0,1.85,0],
               ['armL','chest',0.5,1.6,0],['armR','chest',-0.5,1.6,0],
               ['legL','root',0.25,0.95,0],['legR','root',-0.25,0.95,0]],
      parts: [
        { id:'torso',  kind:'capsule', p:{r:0.34,len:0.6}, pos:[0,1.45,0], role:'primary' },
        { id:'pelvis', kind:'sphere',  p:{r:0.3}, pos:[0,1.05,0], role:'secondary' },
        { id:'head',   kind:'sphere',  p:{r:0.24}, pos:[0,1.95,0], role:'primary', parent:'head' },
        { id:'eyeL',   kind:'sphere',  p:{r:0.045}, pos:[0.09,1.99,0.21], role:'glow', parent:'head' },
        { id:'eyeR',   kind:'sphere',  p:{r:0.045}, pos:[-0.09,1.99,0.21], role:'glow', parent:'head' },
        { id:'arm',    kind:'capsule', p:{r:0.1,len:0.62}, pos:[0.48,1.35,0], rot:[0,0,-0.12], role:'limb', mirror:true, parent:'armL' },
        { id:'hand',   kind:'sphere',  p:{r:0.11}, pos:[0.52,0.85,0], role:'accent', mirror:true, parent:'armL' },
        { id:'leg',    kind:'capsule', p:{r:0.13,len:0.7}, pos:[0.22,0.5,0], role:'limb', mirror:true, parent:'legL' },
        { id:'foot',   kind:'box',     p:{w:0.18,h:0.1,d:0.34}, pos:[0.22,0.06,0.08], role:'secondary', mirror:true, parent:'legL' },
        { id:'shoulderL', kind:'sphere', p:{r:0.16}, pos:[0.44,1.66,0], role:'accent', parent:'armL' },
        { id:'shoulderR', kind:'sphere', p:{r:0.16}, pos:[-0.44,1.66,0], role:'accent', parent:'armR' },
      ],
    },
    hexapod: {
      label: 'Hexapod walker',
      glyph: '🕷',
      keywords: ['hexapod','spider','insect','bug','beetle','ant','scorpion','six leg','multi leg'],
      joints: [['root',0,0.6,0],['body','root',0,0.72,0],['head','body',0,0.7,0.7]],
      parts: [
        { id:'pod',    kind:'capsule', p:{r:0.4,len:0.9}, pos:[0,0.72,0], rot:[Math.PI/2,0,0], role:'primary', parent:'body' },
        { id:'head',   kind:'sphere',  p:{r:0.26}, pos:[0,0.7,0.72], role:'secondary', parent:'head' },
        { id:'eye',    kind:'sphere',  p:{r:0.06}, pos:[0.1,0.78,0.9], role:'glow', mirror:true, parent:'head' },
        { id:'legA',   kind:'cylinder',p:{r:0.05,h:0.55}, pos:[0.42,0.55,0.3], rot:[0,0,0.9], role:'limb', legsAround:6, parent:'body' },
        { id:'legB',   kind:'cylinder',p:{r:0.04,h:0.5}, pos:[0.72,0.28,0.3], rot:[0,0,-1.1], role:'limb', legsAround:6, parent:'body' },
        { id:'mandible',kind:'cone',   p:{r:0.05,h:0.18}, pos:[0.08,0.62,0.95], rot:[Math.PI/2,0,0], role:'accent', mirror:true, parent:'head' },
      ],
    },
    serpentine: {
      label: 'Serpentine / dragon',
      glyph: '🐉',
      keywords: ['dragon','snake','serpent','wyrm','worm','cobra','python','sea serpent'],
      joints: [['root',0,0.5,0],['neck','root',0,0.6,0.6],['head','neck',0,0.7,1.1],['tail','root',0,0.55,-0.8]],
      parts: [
        { id:'coil',   kind:'torus',   p:{R:0.55,r:0.22}, pos:[0,0.45,0], rot:[Math.PI/2,0,0], role:'primary', parent:'root' },
        { id:'neckSeg',kind:'cylinder',p:{r:0.18,h:0.5}, pos:[0,0.6,0.6], rot:[Math.PI/2.6,0,0], role:'primary', parent:'neck' },
        { id:'head',   kind:'cone',    p:{r:0.24,h:0.55}, pos:[0,0.85,1.05], rot:[Math.PI/2,0,0], role:'secondary', parent:'head' },
        { id:'horn',   kind:'cone',    p:{r:0.05,h:0.28}, pos:[0.1,1.0,0.95], role:'accent', mirror:true, parent:'head' },
        { id:'eye',    kind:'sphere',  p:{r:0.05}, pos:[0.12,0.9,1.15], role:'glow', mirror:true, parent:'head' },
        { id:'tailSeg',kind:'cone',    p:{r:0.16,h:0.9}, pos:[0,0.5,-1.0], rot:[-Math.PI/2,0,0], role:'primary', parent:'tail' },
        { id:'spineRow',kind:'cone',   p:{r:0.07,h:0.2}, pos:[0,0.7,0.2], role:'accent', ridgeAlong:'z', ridgeCount:7, parent:'root' },
      ],
    },
    avian: {
      label: 'Avian flyer',
      glyph: '🦅',
      keywords: ['bird','eagle','owl','crow','parrot','falcon','chicken','duck','wing','flappy'],
      joints: [['root',0,0.7,0],['body','root',0,0.8,0],['head','body',0,1.0,0.35],['wingL','body',0.3,0.95,0],['wingR','body',-0.3,0.95,0],['tail','body',0,0.8,-0.45]],
      parts: [
        { id:'body',   kind:'capsule', p:{r:0.28,len:0.5}, pos:[0,0.8,0], rot:[Math.PI/2,0,0], role:'primary', parent:'body' },
        { id:'head',   kind:'sphere',  p:{r:0.2}, pos:[0,1.05,0.38], role:'primary', parent:'head' },
        { id:'beak',   kind:'cone',    p:{r:0.07,h:0.22}, pos:[0,1.02,0.6], rot:[Math.PI/2,0,0], role:'accent', parent:'head' },
        { id:'eye',    kind:'sphere',  p:{r:0.04}, pos:[0.09,1.1,0.48], role:'glow', mirror:true, parent:'head' },
        { id:'wing',   kind:'box',     p:{w:0.85,h:0.05,d:0.4}, pos:[0.5,0.92,-0.02], rot:[0,0,0.18], role:'secondary', mirror:true, parent:'wingL' },
        { id:'tailFeather',kind:'box', p:{w:0.24,h:0.04,d:0.4}, pos:[0,0.78,-0.6], rot:[0.3,0,0], role:'accent', parent:'tail' },
        { id:'leg',    kind:'cylinder',p:{r:0.04,h:0.4}, pos:[0.1,0.4,0.05], role:'limb', mirror:true, parent:'root' },
      ],
    },
    vehicle: {
      label: 'Wheeled vehicle',
      glyph: '🚗',
      keywords: ['car','truck','bus','tank','vehicle','jeep','van','sports car','pickup','race car','automobile'],
      joints: [['root',0,0.35,0],['chassis','root',0,0.45,0],['wheelFL','chassis',0.62,0.3,0.8],['wheelFR','chassis',-0.62,0.3,0.8],['wheelRL','chassis',0.62,0.3,-0.9],['wheelRR','chassis',-0.62,0.3,-0.9]],
      parts: [
        { id:'chassis',kind:'box',   p:{w:1.5,h:0.35,d:2.6}, pos:[0,0.42,0], role:'primary', parent:'chassis' },
        { id:'cabin',  kind:'box',   p:{w:1.25,h:0.45,d:1.1}, pos:[0,0.82,-0.1], role:'secondary', parent:'chassis' },
        { id:'windshield',kind:'box',p:{w:1.15,h:0.4,d:0.06}, pos:[0,0.85,0.55], rot:[-0.5,0,0], role:'glass', parent:'chassis' },
        { id:'wheel',  kind:'cylinder',p:{r:0.3,h:0.22}, pos:[0.62,0.3,0.8], rot:[0,0,Math.PI/2], role:'dark', wheelPositions:[[0.62,0.3,0.8],[-0.62,0.3,0.8],[0.62,0.3,-0.9],[-0.62,0.3,-0.9]], parent:'wheelFL' },
        { id:'hub',    kind:'cylinder',p:{r:0.12,h:0.24}, pos:[0.62,0.3,0.8], rot:[0,0,Math.PI/2], role:'accent', wheelPositions:[[0.62,0.3,0.8],[-0.62,0.3,0.8],[0.62,0.3,-0.9],[-0.62,0.3,-0.9]], parent:'wheelFL' },
        { id:'light',  kind:'sphere',p:{r:0.08}, pos:[0.45,0.5,1.3], role:'glow', mirror:true, parent:'chassis' },
      ],
    },
    aircraft: {
      label: 'Aircraft',
      glyph: '✈',
      keywords: ['plane','airplane','aircraft','jet','glider','biplane','fighter','airliner'],
      joints: [['root',0,0.6,0],['fuselage','root',0,0.6,0],['wingL','fuselage',0.4,0.6,0],['wingR','fuselage',-0.4,0.6,0],['tail','fuselage',0,0.6,-1.4]],
      parts: [
        { id:'fuselage',kind:'capsule',p:{r:0.28,len:2.4}, pos:[0,0.6,0], rot:[Math.PI/2,0,0], role:'primary', parent:'fuselage' },
        { id:'nose',    kind:'cone',   p:{r:0.28,h:0.5}, pos:[0,0.6,1.55], rot:[Math.PI/2,0,0], role:'secondary', parent:'fuselage' },
        { id:'cockpit', kind:'sphere', p:{r:0.2}, pos:[0,0.82,0.8], role:'glass', parent:'fuselage' },
        { id:'wing',    kind:'box',    p:{w:2.6,h:0.06,d:0.7}, pos:[0,0.58,0.15], role:'primary', parent:'wingL' },
        { id:'vstab',   kind:'box',    p:{w:0.06,h:0.6,d:0.5}, pos:[0,1.0,-1.35], role:'secondary', parent:'tail' },
        { id:'hstab',   kind:'box',    p:{w:1.1,h:0.05,d:0.35}, pos:[0,0.68,-1.35], role:'secondary', parent:'tail' },
        { id:'engine',  kind:'cylinder',p:{r:0.16,h:0.5}, pos:[0.8,0.45,0.1], rot:[Math.PI/2,0,0], role:'dark', mirror:true, parent:'wingL' },
      ],
    },
    building: {
      label: 'Building / tower',
      glyph: '🏢',
      keywords: ['building','skyscraper','tower','house','office','block','highrise','apartment','cabin','home'],
      joints: [['root',0,0,0],['base','root',0,0.5,0],['mid','base',0,1.6,0],['top','mid',0,2.8,0]],
      parts: [
        { id:'baseFloor',kind:'box',p:{w:2.0,h:1.0,d:2.0}, pos:[0,0.5,0], role:'masonry', parent:'base' },
        { id:'midFloor', kind:'box',p:{w:1.8,h:1.4,d:1.8}, pos:[0,1.7,0], role:'primary', parent:'mid' },
        { id:'topFloor', kind:'box',p:{w:1.5,h:1.0,d:1.5}, pos:[0,2.9,0], role:'primary', parent:'top' },
        { id:'roof',     kind:'cone',p:{r:1.2,h:0.7}, pos:[0,3.7,0], role:'dark', parent:'top' },
        { id:'door',     kind:'box', p:{w:0.4,h:0.7,d:0.06}, pos:[0,0.35,1.01], role:'accent', parent:'base' },
        { id:'windowRow',kind:'box', p:{w:0.25,h:0.3,d:0.05}, pos:[0.5,1.7,0.91], role:'glass', gridRepeat:{count:3,axis:'x',step:0.5,faces:4}, parent:'mid' },
        { id:'antenna',  kind:'cylinder',p:{r:0.04,h:0.8}, pos:[0,4.4,0], role:'metal', parent:'top' },
      ],
    },
    castle: {
      label: 'Castle fortress',
      glyph: '🏰',
      keywords: ['castle','fortress','citadel','keep','bastion','medieval','fort'],
      joints: [['root',0,0,0],['gate','root',0,0.8,0.9],['towerFL','root',1.0,1.1,1.0],['towerFR','root',-1.0,1.1,1.0],['towerBL','root',1.0,1.1,-1.0],['towerBR','root',-1.0,1.1,-1.0]],
      parts: [
        { id:'wallRing',kind:'box',p:{w:2.6,h:1.2,d:0.3}, pos:[0,0.6,1.05], role:'masonry', wallPerimeter:true, parent:'gate' },
        { id:'gatehouse',kind:'box',p:{w:1.0,h:1.5,d:0.5}, pos:[0,0.75,1.0], role:'primary', parent:'gate' },
        { id:'gateArch',kind:'box',p:{w:0.5,h:0.8,d:0.1}, pos:[0,0.4,1.26], role:'dark', parent:'gate' },
        { id:'tower',   kind:'cylinder',p:{r:0.4,h:2.2}, pos:[1.0,1.1,1.0], role:'masonry', cornerPositions:[[1.0,1.1,1.0],[-1.0,1.1,1.0],[1.0,1.1,-1.0],[-1.0,1.1,-1.0]], parent:'towerFL' },
        { id:'towerRoof',kind:'cone',p:{r:0.48,h:0.7}, pos:[1.0,2.55,1.0], role:'accent', cornerPositions:[[1.0,1.1,1.0],[-1.0,1.1,1.0],[1.0,1.1,-1.0],[-1.0,1.1,-1.0]], parent:'towerFL' },
        { id:'crenel',  kind:'box',p:{w:0.18,h:0.25,d:0.18}, pos:[0,1.32,1.05], role:'masonry', crenelRing:true, parent:'gate' },
        { id:'flagPole',kind:'cylinder',p:{r:0.03,h:0.6}, pos:[0,1.8,1.0], role:'metal', parent:'gate' },
        { id:'flag',    kind:'box',p:{w:0.3,h:0.18,d:0.02}, pos:[0.16,1.95,1.0], role:'glow', parent:'gate' },
      ],
    },
    mechwalker: {
      label: 'Mechanical walker',
      glyph: '🦾',
      keywords: ['mech walker','mecha','giant robot','strider','at,st','walker machine','battle mech','droid'],
      joints: [['root',0,1.2,0],['hip','root',0,1.3,0],['torso','hip',0,1.7,0],['head','torso',0,2.1,0.1],['armL','torso',0.6,1.85,0],['armR','torso',-0.6,1.85,0],['legL','hip',0.35,1.2,0],['legR','hip',-0.35,1.2,0]],
      parts: [
        { id:'torsoBox',kind:'box',p:{w:0.9,h:0.7,d:0.6}, pos:[0,1.75,0], role:'metal', parent:'torso' },
        { id:'cockpit', kind:'sphere',p:{r:0.22}, pos:[0,1.95,0.3], role:'glass', parent:'torso' },
        { id:'headPod', kind:'box',p:{w:0.35,h:0.3,d:0.35}, pos:[0,2.25,0.05], role:'primary', parent:'head' },
        { id:'visor',   kind:'box',p:{w:0.3,h:0.08,d:0.05}, pos:[0,2.28,0.24], role:'glow', parent:'head' },
        { id:'shoulder',kind:'box',p:{w:0.3,h:0.35,d:0.4}, pos:[0.62,1.85,0], role:'primary', mirror:true, parent:'armL' },
        { id:'armUpper',kind:'cylinder',p:{r:0.1,h:0.6}, pos:[0.68,1.35,0], role:'metal', mirror:true, parent:'armL' },
        { id:'armLower',kind:'box',p:{w:0.18,h:0.55,d:0.18}, pos:[0.68,0.8,0.05], role:'secondary', mirror:true, parent:'armL' },
        { id:'hipJoint',kind:'cylinder',p:{r:0.16,h:0.5}, pos:[0,1.25,0], rot:[0,0,Math.PI/2], role:'dark', parent:'hip' },
        { id:'thigh',   kind:'box',p:{w:0.24,h:0.7,d:0.3}, pos:[0.32,0.8,0], role:'primary', mirror:true, parent:'legL' },
        { id:'shin',    kind:'box',p:{w:0.18,h:0.65,d:0.22}, pos:[0.32,0.25,0.08], role:'metal', mirror:true, parent:'legL' },
        { id:'footPad', kind:'box',p:{w:0.3,h:0.12,d:0.5}, pos:[0.32,-0.05,0.12], role:'dark', mirror:true, parent:'legL' },
      ],
    },
    spaceship: {
      label: 'Starship',
      glyph: '🚀',
      keywords: ['spaceship','starship','rocket','spacecraft','shuttle','satellite','probe','ufo','saucer'],
      joints: [['root',0,0.6,0],['hull','root',0,0.6,0],['engine','root',0,0.6,-1.1],['finL','hull',0.4,0.6,-0.8],['finR','hull',-0.4,0.6,-0.8]],
      parts: [
        { id:'hull',    kind:'capsule',p:{r:0.35,len:1.6}, pos:[0,0.6,0], rot:[Math.PI/2,0,0], role:'primary', parent:'hull' },
        { id:'noseCone',kind:'cone',p:{r:0.35,h:0.6}, pos:[0,0.6,1.35], rot:[Math.PI/2,0,0], role:'secondary', parent:'hull' },
        { id:'cockpitDome',kind:'sphere',p:{r:0.2}, pos:[0,0.85,0.6], role:'glass', parent:'hull' },
        { id:'ring',    kind:'torus',p:{R:0.6,r:0.07}, pos:[0,0.6,-0.1], rot:[Math.PI/2,0,0], role:'metal', parent:'hull' },
        { id:'engineBlock',kind:'box',p:{w:0.5,h:0.5,d:0.4}, pos:[0,0.6,-1.05], role:'dark', parent:'engine' },
        { id:'thruster',kind:'cone',p:{r:0.14,h:0.3}, pos:[0.15,0.6,-1.35], rot:[-Math.PI/2,0,0], role:'glow', triple:{axis:'x',step:0.3}, parent:'engine' },
        { id:'fin',     kind:'box',p:{w:0.06,h:0.5,d:0.5}, pos:[0.38,0.75,-0.85], rot:[0,0,0.35], role:'accent', mirror:true, parent:'finL' },
      ],
    },
    furniture: {
      label: 'Furniture piece',
      glyph: '🪑',
      keywords: ['chair','table','desk','stool','sofa','couch','bed','bench','shelf','wardrobe','furniture'],
      joints: [['root',0,0.4,0],['seat','root',0,0.45,0],['backrest','seat',0,0.75,-0.22]],
      parts: [
        { id:'seatTop', kind:'box',p:{w:0.7,h:0.08,d:0.7}, pos:[0,0.45,0], role:'primary', parent:'seat' },
        { id:'backPanel',kind:'box',p:{w:0.7,h:0.7,d:0.08}, pos:[0,0.85,-0.31], rot:[-0.12,0,0], role:'primary', parent:'backrest' },
        { id:'legPost', kind:'cylinder',p:{r:0.04,h:0.45}, pos:[0.3,0.22,0.3], role:'dark', legCorners:true, parent:'root' },
        { id:'brace',   kind:'box',p:{w:0.6,h:0.04,d:0.04}, pos:[0,0.2,0.3], role:'secondary', braceRing:true, parent:'root' },
      ],
    },
    weaponblade: {
      label: 'Bladed weapon',
      glyph: '⚔',
      keywords: ['sword','axe','knife','blade','dagger','halberd','weapon','spear','lance'],
      joints: [['root',0,0.5,0],['grip','root',0,0.35,0],['guard','root',0,0.62,0],['bladeRoot','guard',0,0.75,0],['tip','bladeRoot',0,1.6,0]],
      parts: [
        { id:'pommel',  kind:'sphere',p:{r:0.07}, pos:[0,0.12,0], role:'accent', parent:'grip' },
        { id:'gripShaft',kind:'cylinder',p:{r:0.045,h:0.4}, pos:[0,0.35,0], role:'dark', parent:'grip' },
        { id:'crossGuard',kind:'box',p:{w:0.4,h:0.06,d:0.08}, pos:[0,0.6,0], role:'metal', parent:'guard' },
        { id:'blade',   kind:'box',p:{w:0.14,h:0.95,d:0.03}, pos:[0,1.1,0], role:'metal', parent:'bladeRoot' },
        { id:'bladeTip',kind:'cone',p:{r:0.07,h:0.22}, pos:[0,1.68,0], role:'metal', parent:'tip' },
        { id:'fuller',  kind:'box',p:{w:0.03,h:0.85,d:0.04}, pos:[0,1.1,0.01], role:'glow', parent:'bladeRoot' },
      ],
    },
    tree: {
      label: 'Tree / flora',
      glyph: '🌳',
      keywords: ['tree','plant','palm','oak','pine','forest','flora','bonsai','bush','shrub'],
      joints: [['root',0,0,0],['trunkJ','root',0,0.9,0],['canopyJ','trunkJ',0,1.8,0]],
      parts: [
        { id:'trunk',   kind:'cylinder',p:{r:0.16,h:1.5}, pos:[0,0.75,0], role:'dark', taper:0.6, parent:'trunkJ' },
        { id:'canopyA', kind:'sphere',p:{r:0.7}, pos:[0,1.9,0], role:'primary', parent:'canopyJ' },
        { id:'canopyB', kind:'sphere',p:{r:0.5}, pos:[0.5,1.6,0.3], role:'secondary', parent:'canopyJ' },
        { id:'canopyC', kind:'sphere',p:{r:0.45}, pos:[-0.45,1.75,-0.3], role:'secondary', parent:'canopyJ' },
        { id:'branch',  kind:'cylinder',p:{r:0.05,h:0.6}, pos:[0.3,1.3,0], rot:[0,0,-0.8], role:'dark', mirror:true, parent:'trunkJ' },
        { id:'rootFlare',kind:'cone',p:{r:0.18,h:0.3}, pos:[0.2,0.08,0.1], rot:[Math.PI,0,0], role:'dark', radialCount:5, parent:'root' },
      ],
    },
    creature_winged: {
      label: 'Winged creature',
      glyph: '🦇',
      keywords: ['bat','gargoyle','griffin','pegasus','wyvern','fairy','angel','demon'],
      joints: [['root',0,0.7,0],['bodyJ','root',0,0.8,0],['headJ','bodyJ',0,1.05,0.35],['wingL','bodyJ',0.25,0.95,-0.05],['wingR','bodyJ',-0.25,0.95,-0.05]],
      parts: [
        { id:'bodyW',   kind:'capsule',p:{r:0.25,len:0.5}, pos:[0,0.8,0], rot:[Math.PI/2,0,0], role:'primary', parent:'bodyJ' },
        { id:'headW',   kind:'sphere',p:{r:0.18}, pos:[0,0.95,0.42], role:'primary', parent:'headJ' },
        { id:'earBat',  kind:'cone',p:{r:0.07,h:0.22}, pos:[0.1,1.12,0.4], role:'accent', mirror:true, parent:'headJ' },
        { id:'eyeGlow', kind:'sphere',p:{r:0.035}, pos:[0.07,0.98,0.56], role:'glow', mirror:true, parent:'headJ' },
        { id:'wingMembrane',kind:'box',p:{w:1.0,h:0.03,d:0.55}, pos:[0.6,0.95,-0.05], rot:[0,0,0.25], role:'secondary', mirror:true, parent:'wingL' },
        { id:'wingBone',kind:'cylinder',p:{r:0.035,h:1.0}, pos:[0.55,1.05,-0.05], rot:[0,0,Math.PI/2-0.25], role:'dark', mirror:true, parent:'wingL' },
        { id:'claw',    kind:'cone',p:{r:0.04,h:0.12}, pos:[0,0.62,0.3], role:'accent', triple:{axis:'x',step:0.12}, parent:'bodyJ' },
      ],
    },
    dino: {
      label: 'Dinosaur',
      glyph: '🦖',
      keywords: ['dinosaur','dino','trex','raptor','rex','sauropod','triceratops','jurassic','velociraptor'],
      joints: [['root',0,0.9,0],['hips','root',0,1.0,-0.2],['spineJ','hips',0,1.1,0.2],['neckJ','spineJ',0,1.25,0.6],['headJ','neckJ',0,1.35,1.0],['tailJ','hips',0,1.0,-0.8],['legL','hips',0.3,0.9,-0.1],['legR','hips',-0.3,0.9,-0.1]],
      parts: [
        { id:'dBody',   kind:'capsule',p:{r:0.4,len:0.9}, pos:[0,1.05,0], rot:[Math.PI/2,0,0], role:'primary', parent:'spineJ' },
        { id:'dHead',   kind:'box',p:{w:0.34,h:0.34,d:0.6}, pos:[0,1.35,1.15], role:'primary', parent:'headJ' },
        { id:'jaw',     kind:'box',p:{w:0.3,h:0.12,d:0.5}, pos:[0,1.14,1.18], role:'secondary', parent:'headJ' },
        { id:'tooth',   kind:'cone',p:{r:0.03,h:0.09}, pos:[0.08,1.2,1.35], rot:[Math.PI,0,0], role:'accent', gridRepeat:{count:4,axis:'x',step:0.055,faces:1}, parent:'headJ' },
        { id:'eyeD',    kind:'sphere',p:{r:0.045}, pos:[0.15,1.42,1.05], role:'glow', mirror:true, parent:'headJ' },
        { id:'dArm',    kind:'cylinder',p:{r:0.06,h:0.3}, pos:[0.28,1.15,0.45], rot:[0.4,0,-0.4], role:'limb', mirror:true, parent:'spineJ' },
        { id:'dLeg',    kind:'capsule',p:{r:0.14,len:0.55}, pos:[0.3,0.55,-0.1], role:'limb', mirror:true, parent:'legL' },
        { id:'dFoot',   kind:'box',p:{w:0.22,h:0.1,d:0.36}, pos:[0.3,0.08,0.05], role:'dark', mirror:true, parent:'legL' },
        { id:'dTail',   kind:'cone',p:{r:0.3,h:1.4}, pos:[0,1.0,-1.3], rot:[-Math.PI/2,0,0], role:'primary', parent:'tailJ' },
        { id:'crestSpine',kind:'cone',p:{r:0.06,h:0.16}, pos:[0,1.42,0.3], role:'accent', ridgeAlong:'z', ridgeCount:6, parent:'spineJ' },
      ],
    },
    tankVehicle: {
      label: 'Tracked tank',
      glyph: '🛡',
      keywords: ['military tank','panzer','tracked','howitzer','armored personnel','tread'],
      joints: [['root',0,0.45,0],['hullJ','root',0,0.5,0],['turretJ','hullJ',0,0.85,0],['barrelJ','turretJ',0,0.85,0.5]],
      parts: [
        { id:'hullT',   kind:'box',p:{w:1.5,h:0.45,d:2.4}, pos:[0,0.42,0], role:'primary', parent:'hullJ' },
        { id:'turret',  kind:'cylinder',p:{r:0.5,h:0.35}, pos:[0,0.85,0], role:'secondary', parent:'turretJ' },
        { id:'barrel',  kind:'cylinder',p:{r:0.08,h:1.3}, pos:[0,0.88,1.0], rot:[Math.PI/2,0,0], role:'dark', parent:'barrelJ' },
        { id:'muzzle',  kind:'cylinder',p:{r:0.12,h:0.2}, pos:[0,0.88,1.62], rot:[Math.PI/2,0,0], role:'metal', parent:'barrelJ' },
        { id:'trackFrame',kind:'box',p:{w:0.3,h:0.4,d:2.5}, pos:[0.72,0.25,0], role:'dark', mirror:true, parent:'root' },
        { id:'roadWheel',kind:'cylinder',p:{r:0.16,h:0.1}, pos:[0.72,0.18,0.8], rot:[0,0,Math.PI/2], role:'metal', gridRepeat:{count:5,axis:'z',step:0.4,faces:2}, parent:'root' },
        { id:'hatch',   kind:'cylinder',p:{r:0.16,h:0.06}, pos:[0,1.06,0], role:'metal', parent:'turretJ' },
      ],
    },
    ufoCraft: {
      label: 'Disc craft',
      glyph: '🛸',
      keywords: ['flying saucer','disc','ufO'.toLowerCase(),'alien ship',' mothership'],
      joints: [['root',0,0.6,0],['domeJ','root',0,0.8,0],['rimJ','root',0,0.55,0]],
      parts: [
        { id:'saucer',  kind:'sphere',p:{r:1.0}, pos:[0,0.5,0], scale:[1,0.22,1], role:'metal', parent:'rimJ' },
        { id:'dome',    kind:'sphere',p:{r:0.42}, pos:[0,0.72,0], scale:[1,0.75,1], role:'glass', parent:'domeJ' },
        { id:'beamRing',kind:'torus',p:{R:0.85,r:0.06}, pos:[0,0.42,0], rot:[Math.PI/2,0,0], role:'glow', parent:'rimJ' },
        { id:'podLight',kind:'sphere',p:{r:0.09}, pos:[0.85,0.5,0], role:'glow', radialCount:8, parent:'rimJ' },
        { id:'tractorBeam',kind:'cone',p:{r:0.5,h:0.8}, pos:[0,0.0,0], rot:[Math.PI,0,0], role:'glass', opacity:0.25, parent:'root' },
      ],
    },
    robot_tall: {
      label: 'Tall sentinel robot',
      glyph: '🗿',
      keywords: ['sentinel','colossus','golem robot','statue robot','monolith bot','watcher'],
      joints: [['root',0,1.4,0],['pelvJ','root',0,1.5,0],['chestJ','pelvJ',0,2.2,0],['headJ','chestJ',0,2.8,0],['armL','chestJ',0.7,2.3,0],['armR','chestJ',-0.7,2.3,0]],
      parts: [
        { id:'stTorso', kind:'box',p:{w:1.0,h:1.1,d:0.55}, pos:[0,2.15,0], role:'masonry', parent:'chestJ' },
        { id:'coreOrb', kind:'sphere',p:{r:0.18}, pos:[0,2.3,0.3], role:'glow', parent:'chestJ' },
        { id:'stHead',  kind:'box',p:{w:0.45,h:0.5,d:0.4}, pos:[0,2.95,0], role:'primary', parent:'headJ' },
        { id:'stEye',   kind:'box',p:{w:0.3,h:0.06,d:0.05}, pos:[0,3.0,0.21], role:'glow', parent:'headJ' },
        { id:'stArm',   kind:'capsule',p:{r:0.14,len:1.2}, pos:[0.72,1.9,0], role:'masonry', mirror:true, parent:'armL' },
        { id:'stFist',  kind:'sphere',p:{r:0.2}, pos:[0.72,1.05,0], role:'metal', mirror:true, parent:'armL' },
        { id:'stLeg',   kind:'box',p:{w:0.32,h:1.3,d:0.4}, pos:[0.28,0.65,0], role:'masonry', mirror:true, parent:'root' },
        { id:'stShoulder',kind:'box',p:{w:0.4,h:0.3,d:0.6}, pos:[0.66,2.55,0], role:'accent', mirror:true, parent:'armL' },
      ],
    },
  };

  /* -------- primitive kinds understood by builder -------- */
  const PRIMITIVES = ['box','sphere','capsule','cylinder','cone','torus'];

  /* -------- color roles -------- */
  const ROLE_COLORS = {
    primary:  '#4db8ff',
    secondary:'#3a6ea5',
    accent:   '#ffb454',
    dark:     '#2b3446',
    metal:    '#9aa7b8',
    glow:     '#37e0b0',
    glass:    '#bfe8ff',
    limb:     '#54637d',
    masonry:  '#b8a68a',
  };

  /* -------- organic palettes (used when style=organic) -------- */
  const PALETTES = {
    organic:  { primary:'#7fb069', secondary:'#5c8d4f', accent:'#e0dfa6', dark:'#4a3f35', limb:'#6b5b4a', glow:'#ffd166', masonry:'#7fb069', metal:'#8a9a5b', glass:'#d8f3d3' },
    lowpoly:  { primary:'#f28f3b', secondary:'#c86b2c', accent:'#642754', dark:'#3e2b4f', limb:'#845d8f', glow:'#d9ed92', masonry:'#e8ac6c', metal:'#e8ac6c', glass:'#ffe1a8' },
    mech:     null, // uses defaults
    architecture: null,
  };

  /* -------- search corpus: factual references -------- */
  const FACTS = [
    { topic:'gray wolf proportions', body:'Adult gray wolf shoulder height ≈ 66–81 cm; body length ≈ 105–160 cm; head ≈ 25% of shoulder height. Leg length ≈ 55% of shoulder height.', tags:['wolf','dog','quadruped'] },
    { topic:'horse proportions', body:'Draft horse withers ≈ 160–170 cm; leg ≈ 45% of total height; body depth ≈ 50% of height.', tags:['horse','quadruped'] },
    { topic:'human anatomy ratio', body:'Classic canon: 8 heads tall. Head ≈ 12.5% of height; shoulder span ≈ 2 heads; leg ≈ 48% of height.', tags:['human','bipedal','proportion'] },
    { topic:'T-Rex dimensions', body:'T. rex hip height ≈ 3.1 m; total length ≈ 12 m; skull ≈ 1.5 m. Tail ≈ 40% of total length.', tags:['trex','dino','dinosaur'] },
    { topic:'eagle wingspan', body:'Golden eagle wingspan 1.8–2.3 m ≈ 2.5× body length. Wings attach at shoulder, sweep back ~20°.', tags:['eagle','bird','avian','wing'] },
    { topic:'sedan car dimensions', body:'Mid-size sedan: length 4.7 m, width 1.85 m, height 1.45 m, wheelbase 2.7 m, wheel Ø ≈ 0.65 m, ride height 0.15 m.', tags:['car','vehicle','sedan'] },
    { topic:'main battle tank', body:'Leopard 2: hull length 7.7 m, width 3.7 m, height 1.67 m (3.0 with turret optics). Barrel ≈ 5.5 m for L/55 gun.', tags:['tank','military'] },
    { topic:'medieval castle keep', body:'Keep height typically 9–15 m (3–5 stories); walls 2.4–3.7 m thick; towers 1.5× keep height; crenel merlons ≈ 0.6–0.9 m tall.', tags:['castle','architecture'] },
    { topic:'skyscraper ratios', body:'Typical floor-to-floor height 3.7–4.2 m; slender towers width:height ≈ 1:6 to 1:8; podium ≈ 10% of height.', tags:['skyscraper','building'] },
    { topic:'oak tree structure', body:'Mature oak: trunk Ø 0.9–1.5 m, height 18–28 m, canopy spread ≈ 0.8× height; canopy begins at 45% of height.', tags:['tree','oak','flora'] },
    { topic:'dragon myth design', body:'Western dragon: wingspan ≈ 3× body; four limbs plus wings; tail ≈ 1.5× body+head combined; horns swept back 30–45°.', tags:['dragon','serpentine','wyvern'] },
    { topic:'hexapod robotics', body:'Hexapods use 6 legs phased in tripod gaits; leg segments coxa/femur/tibia ≈ 1:2:2.5; stride ≈ 1.5× body length.', tags:['hexapod','robot','spider'] },
    { topic:'spaceship design tropes', body:'Nostromo-style industrial hull: length:beam ≈ 6:1; rotating ring radius ≈ 0.35× length; engine cluster aft 15%.', tags:['spaceship','rocket','sci-fi'] },
    { topic:'sword forging', body:'European longsword: blade 90–110 cm, grip 25–30 cm, pommel ≈ 6% of total mass; blade tapers to distal triangle.', tags:['sword','weaponblade'] },
    { topic:'mech design (artbook canon)', body:'Battle mech: cockpit at 60–70% height; leg travel ≈ 45% height; shoulder armor widest point ≈ 1.4× torso width.', tags:['mech','mechwalker','robot'] },
    { topic:'bat wing anatomy', body:'Bat wingspan ≈ 2–3× body length; membrane supported by 4 elongated digits; leading-edge bone ≈ 0.9× wingspan/2.', tags:['bat','creature_winged'] },
    { topic:'furniture ergonomics', body:'Dining chair seat height 43–46 cm; seat 45×45 cm; backrest rises 30–40 cm above seat at 95–100°.', tags:['chair','furniture'] },
    { topic:'UFO classic disc', body:'Flying-saucer trope: rim diameter 9–12 m; dome ≈ 0.4× rim; rim lights evenly spaced every 45°.', tags:['ufo','flying saucer'] },
    { topic:'aircraft biplane', body:'WWI fighter: wingspan ≈ 8 m, length 6–7 m; stagger between wings ≈ 1.2 m; tailplane ≈ 25% of main wing area.', tags:['aircraft','plane'] },
    { topic:'quadruped gait cycles', body:'Walk sequence FL→HR→FR→HL, duty factor ≈ 0.6; spine flex ±5° adds reach; tail counterbalances pitch.', tags:['quadruped','animation','gait'] },
  ];

  window.Knowledge = { ARCHETYPES, PRIMITIVES, ROLE_COLORS, PALETTES, FACTS };
})();
